import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Provider } from 'react-redux';
import Header from '@/components/Header';
import { store } from '@/store/store';
import ReduxProvider from '@/store/redux-provider';
import Footer from '@/components/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // get paht from url then get permission on each path
  // call usePermissionCheck with param from above
  // const path = 'account' => permisison= 'account'
  //  usePermissionCheck(permisison);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-900 antialiased`}
      >
        <ReduxProvider>
          <Header />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
